"""add_clearance_submitted_to_subscriptions

Revision ID: 13fb030656f9
Revises: 6981e51edfd3
Create Date: 2026-04-15 11:25:14.619757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13fb030656f9'
down_revision: Union[str, Sequence[str], None] = '6981e51edfd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('clearance_submitted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'clearance_submitted')
    # ### end Alembic commands ###
