"""Add onboarding fields to users

Revision ID: 3eb8003ca203
Revises: 93099bc0906c
Create Date: 2026-04-01 08:50:48.519298

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '3eb8003ca203'
down_revision: Union[str, Sequence[str], None] = '93099bc0906c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
