"""Add proof_of_address_url to KYC

Revision ID: 6981e51edfd3
Revises: cc86e50361d2
Create Date: 2026-04-14 02:33:35.916623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6981e51edfd3'
down_revision: Union[str, Sequence[str], None] = 'cc86e50361d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc', sa.Column('proof_of_address_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kyc', 'proof_of_address_url')
    # ### end Alembic commands ###
