"""auth refactor - nullable fields onboarding step

Revision ID: 93099bc0906c
Revises: e850272951d5
Create Date: 2026-03-18 23:17:52.719655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93099bc0906c'
down_revision: Union[str, Sequence[str], None] = 'e850272951d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the enum type first
    onboardingstep = sa.Enum(
        'REGISTERED', 'EMAIL_VERIFIED', 'PASSWORD_SET', 'BASIC_INFO',
        'NIN_SUBMITTED', 'BVN_SUBMITTED', 'PROFILE_UPLOADED', 'COMPLETED',
        name='onboardingstep',
    )
    onboardingstep.create(op.get_bind(), checkfirst=True)

    op.add_column('users', sa.Column('date_of_birth', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('profile_image_url', sa.Text(), nullable=True))
    op.add_column('users', sa.Column(
        'onboarding_step',
        onboardingstep,
        nullable=False,
        server_default='REGISTERED',
    ))
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('users', 'onboarding_step')
    op.drop_column('users', 'profile_image_url')
    op.drop_column('users', 'address')
    op.drop_column('users', 'date_of_birth')
    sa.Enum(name='onboardingstep').drop(op.get_bind(), checkfirst=True)
