"""add_phone_verified_onboarding_step

Revision ID: caccc3f650ec
Revises: 3eb8003ca203
Create Date: 2026-04-06 00:17:50.048162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caccc3f650ec'
down_revision: Union[str, Sequence[str], None] = '3eb8003ca203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
