"""Add wallet_bypass to Account

Revision ID: cc86e50361d2
Revises: 9e3cd4ecb5f8
Create Date: 2026-04-14 01:33:59.272970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc86e50361d2'
down_revision: Union[str, Sequence[str], None] = '9e3cd4ecb5f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('wallet_bypass', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # Remove the server default if not needed afterwards
    op.alter_column('accounts', 'wallet_bypass', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'wallet_bypass')
    # ### end Alembic commands ###
