"""Add ticket models

Revision ID: e9f0a3bdd47d
Revises: caccc3f650ec
Create Date: 2026-04-10 10:49:19.615289

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'e9f0a3bdd47d'
down_revision: Union[str, Sequence[str], None] = 'caccc3f650ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
